owner: calkit
name: example-r
title: R example
description: An example Calkit project that uses R.
git_repo_url: https://github.com/calkit/example-r

environments:
  main:
    kind: renv
    path: DESCRIPTION

pipeline:
  stages:
    analysis:
      kind: r-script
      script_path: R/analysis.R
      environment: main
      inputs:
        - R/load_data.R
      outputs:
        - path: output/analysis_results.rds
          storage: git
