owner: calkit
name: example-r
title: R example
description: An example Calkit project that uses R.
git_repo_url: https://github.com/calkit/example-r

environments:
  main:
    kind: renv
    path: DESCRIPTION

pipeline:
  stages:
    analyze:
      kind: r-script
      script_path: R/analyze.R
      environment: main
      inputs:
        - data/raw/data.csv
      outputs:
        - path: output/analysis_results.rds
          storage: git
        - path: data/processed/data.csv
          storage: git
    plot:
      kind: r-script
      script_path: R/plot.R
      environment: main
      inputs:
        - data/processed/data.csv
      outputs:
        - path: figures/boxplot.pdf
          storage: git
        - path: figures/timeseries.pdf
          storage: git

figures:
  - path: figures/boxplot.pdf
    title: Boxplot
    stage: plot
  - path: figures/timeseries.pdf
    title: Time series
    stage: plot

showcase:
  - figure: figures/boxplot.pdf
  - figure: figures/timeseries.pdf
